### ISSUE TITLE
Releasing: Checklist for submodule splitting

### ISSUE THREAD

**Issue by jakobploens** [minerva-erp/core#14]
- [ ] Add comments to model methods
- [ ] Add better descriptions to GraphQL Types, Queries and Mutations
- [ ] Add `$fillable`-attribute to each model to enable attribute logging
- [ ] Hold migrations and seeds
- [ ] Ensure migration compability with other modules (order of loading, dependency columns, …)
- [ ] Publish settings when needed
- [ ] Publish permissions when needed
- [ ] Publish migration when needed
